# Generated by Django 3.2a1 on 2021-02-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=10)),
                ('gpa', models.FloatField(max_length=3)),
                ('semester', models.CharField(max_length=20)),
            ],
        ),
    ]
